# Generated by Django 5.2.14 on 2026-05-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('prompt', models.CharField(max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('multiple_choice', 'Multiple choice'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('slider', 'Slider')], max_length=32)),
                ('placeholder', models.CharField(blank=True, max_length=160)),
                ('required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('min_label', models.CharField(blank=True, max_length=80)),
                ('max_label', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['step', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('income_range', models.CharField(blank=True, max_length=120)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('district_city', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('value', models.CharField(max_length=120)),
                ('score', models.FloatField(default=0)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='analytics.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BehaviourScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('risk_score', models.FloatField(default=0)),
                ('investor_type', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_score', to='analytics.respondent')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_slug', models.CharField(max_length=120)),
                ('question_prompt', models.CharField(max_length=255)),
                ('answer_text', models.TextField(blank=True)),
                ('answer_number', models.FloatField(blank=True, null=True)),
                ('answer_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='analytics.question')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='analytics.respondent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_preferences', to='analytics.respondent')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='analytics_s_name_5444d1_idx')],
            },
        ),
    ]
